# Numpy Array

In [1]:
import numpy as np

In [2]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.linspace(0,11,5)

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [9]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [10]:
arr.argmax()

0

In [11]:
arr.argmin()

7

In [12]:
arr.min()

9

In [13]:
arr.max()

95

In [15]:
arr.mean()

60.8

In [16]:
mat = np.arange(0,100).reshape(10,10)

In [17]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
row = 0
col = 1

In [19]:
mat[row,col]

1

In [20]:
mat[row][col]

1

In [21]:
mat[:,col]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [22]:
mat[:,col:col+1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [23]:
mat[1:4,1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [25]:
mat[[6,4,2],1:6:2]

array([[61, 63, 65],
       [41, 43, 45],
       [21, 23, 25]])